### ISSUE TITLE
`datatype: ThreePartsDate` 

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-HousingCodeChecklist#363]
Is there a reason `datatype: ThreePartsDate` is used multiple times? 

I think the calendar option is much more user friendly and the year requires 4 numbers but only shows on screen space for two. It looks like only month is required. I think this should be changed to just `datatype: date`

![Screen Shot 2023-04-05 at 3 28 42 PM](https://user-images.githubusercontent.com/65858862/230186250-04c88550-41f4-4646-bf2a-8f0361805177.png)

**Comment by miabonardi** [comment]
Looks like this might be a bug

**Comment by miabonardi** [comment]
https://www.nngroup.com/articles/date-input/

**Comment by plocket** [comment]
The problem is in your styles.css, the first rule:
```css
.form-control {
  padding: .75rem 1rem;
}
```

This creates the padding (hard to see because it's white inside the field) that hides the numbers (and also makes the fields extra tall). If you want to keep that new padding for other elements, you can keep that and add a more specific rule just for these ThreePartDate fields to use the same values as bootstrap:
```css
.form-control {
  padding: .75rem 1rem;
}

.da-field-container-datatype-ThreePartsDate .form-control {
  padding: 0.375rem 0.75rem;
}
```
